src/WebApplication3/Models/PhoneSpotting.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication3.Models
{
    public class PhoneSpotting
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int PhoneSpottingId { get; set; }
        public DateTime SpotTime { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public string PhoneManufacturer { get; set; }
        public string PhoneModel { get; set; }
        public string Notes { get; set; }
    }
}

src/WebApplication3/Models/PhoneSpottingsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication3.Models
{
    public class PhoneSpottingsViewModel
    {
        public List<PhoneSpotting> Spottings { get; set; }
    }
}

src/WebApplication3/Controllers/PhoneSpottingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using WebApplication3.Models;
using Microsoft.AspNet.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace WebApplication3.Controllers
{
    public class PhoneSpottingController : Controller
    {
        private PhoneSpottingContext _spottingContext;
        public PhoneSpottingController(PhoneSpottingContext context)
        {
            _spottingContext = context;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View(new PhoneSpottingsViewModel { Spottings = _spottingContext.Spottings.ToList() });
        }

        // GET: /<controller>/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Create(PhoneSpotting newSpotting)
        {
            if (ModelState.IsValid)
            {
                _spottingContext.Spottings.Add(newSpotting);
                _spottingContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(newSpotting);
        }

    }
}

src/WebApplication3/Views/PhoneSpotting/Create.cshtml
@model PhoneSpotting
@using WebApplication3.Controllers
@{
    ViewBag.Title = "Create New Windows Phone Spotting";
}

<h1>Log Windows Phone Spotting!</h1>

<form asp-controller="PhoneSpotting" asp-action="Create" method="post" class="form-horizontal">
    <div class="form-group">
        <label asp-for="PhoneManufacturer" class="control-label col-xs-2">Manufacturer:</label>
        <div class="col-xs-10">
            <input asp-for="PhoneManufacturer" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <label asp-for="PhoneModel" class="control-label col-xs-2">Model:</label>
        <div class="col-xs-10">
            <input asp-for="PhoneModel" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Latitude" class="control-label col-xs-2">Latitude:</label>
        <div class="col-xs-10">
            <input asp-for="Latitude" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Longitude" class="control-label col-xs-2">Longitude:</label>
        <div class="col-xs-10">
            <input asp-for="Longitude" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label asp-for="SpotTime" class="control-label col-xs-2">Date &amp; Time:</label>
        <div class="col-xs-10">
            <input type="text" asp-for="SpotTime" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Notes" class="control-label col-xs-2">Notes:</label>
        <div class="col-xs-10">
            <textarea asp-for="Notes" class="form-control"></textarea>
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
            <button type="submit" class="btn btn-primary">Login</button>
        </div>
    </div>
</form>

@section Scripts {
`
<script src="~/scripts/phoneSpotter.js"></script>
}

src/WebApplication3/Views/PhoneSpotting/Index.cshtml
@model PhoneSpottingsViewModel
@using WebApplication3.Controllers
@{
    ViewBag.Title = "Windows Phone Spotting List";
}

<h1>Windows Phone Spottings</h1>

<a asp-controller="PhoneSpotting" asp-action="Create">Log New Spotting</a> 
@foreach (var spotting in Model.Spottings)
{
<div>
    <h2>@spotting.PhoneManufacturer @spotting.PhoneModel</h2>
    <div class="spotting-date">@spotting.SpotTime</div>
    <div class="spotting-location">
        <span class="coordinate-name">Latitude:</span><span class="coordinate">@spotting.Latitude</span>
        <span class="coordinate-name">Longitude:</span><span class="coordinate">@spotting.Longitude</span>
        <div>Spotting Notes:</div>
        <div>@spotting.Notes</div>

    </div>
</div>

}